name: String Core Baker
run-name: ${{ github.actor }} updated a core file~ ⚙️
on:
  push:
    paths:
      - 'string-core/**'
  workflow_dispatch:
jobs:
  Bake-String-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Sparse Checkout~ 📋
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .baked
            string-core

      - name: Fetching json files~ 📃
        run: |
          python ./.baked/string.py

      - name: Commiting changes! 📦️
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add ./.baked/*
          git commit -m 'Baked string data'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
